# crie um programa que leia algo e mostre na tela o seu tipo e todas as informações possiveis sobre ele: 
v = input('Digite algo: ')
resultado = type(v)
numero = v.isnumeric()
texto = v.isalpha()
alfanumerico = v.isalnum()
maisculo = v.isupper()
minusculo = v.islower()
espaco = v.isspace()
capitalizado = v.istitle()
print('a tipagem desse dado é {}'.format(resultado))
print('esse dado é do tipo numerico? {}'.format(numero))
print('esse daddo é do tipo alfanumerico?{}'.format(alfanumerico))
print('esse dado é do tipo texto?{}'.format(texto))
print('esse dado esta em maiscula?{}'.format(maisculo))
print('esse dado esta em minuscula?{}'.format(minusculo))
print('esse dado contem somente espaços vazios?{}'.format(espaco))
print('esse dado esta capitalizado?{}'.format(capitalizado))

